repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-json
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 8f9b4931b9a28896fb43edccb23016a7540f5b82
      hooks:
        -   id: flake8
  - repo: local
    hooks:
      - id: system
        name: requirements-dev
        entry: poetry export --format=requirements.txt --without-hashes --with dev --output=requirements-dev.txt
        pass_filename: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: requirements
        entry: poetry export --format=requirements.txt --without-hashes --output=requirements.txt
        pass_filename: false
        language: system